In [17]:
!pip install Sastrawi

Requirement already satisfied: Sastrawi in /usr/local/lib/python3.13/dist-packages (1.0.1)

In [18]:
# Nama: Abid Sabri Zaki
# NIM : 240210502022

import re
import pandas as pd

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

In [19]:
data = {
    'Dokumen': [
        "Keamanan siber sangat penting untuk melindungi data pribadi dan sistem komputer dari serangan berbahaya.",

        "Internet of Things memungkinkan berbagai perangkat terhubung ke internet dan saling bertukar data secara otomatis.",

        "Perpustakaan digital menyediakan berbagai koleksi buku elektronik yang dapat diakses mahasiswa melalui jaringan internet.",

        "Komputasi awan menyediakan layanan penyimpanan dan pengolahan data melalui jaringan internet tanpa harus menggunakan perangkat keras sendiri.",

        "E-Commerce memudahkan masyarakat melakukan transaksi jual beli secara online dengan menggunakan berbagai metode pembayaran digital."
    ]
}

df = pd.DataFrame(data)

df

                                             Dokumen
0  Keamanan siber sangat penting untuk melindungi...
1  Internet of Things memungkinkan berbagai peran...
2  Perpustakaan digital menyediakan berbagai kole...
3  Komputasi awan menyediakan layanan penyimpanan...
4  E-Commerce memudahkan masyarakat melakukan tra...

In [20]:
# Membuat stemmer
stemmer_factory = StemmerFactory()
stemmer = stemmer_factory.create_stemmer()

# Membuat stopword remover
stopword_factory = StopWordRemoverFactory()
stopword_remover = stopword_factory.create_stop_word_remover()

In [21]:
def preprocess_text(text):
    # 1. Case Folding
    text = text.lower()

    # 2. Membersihkan angka
    text = re.sub(r'\d+', '', text)

    # 3. Membersihkan tanda baca dan karakter khusus
    text = re.sub(r'[^a-z\s]', '', text)

    # 4. Menghapus spasi berlebih
    text = re.sub(r'\s+', ' ', text).strip()

    # 5. Tokenisasi
    tokens = text.split()

    # 6. Stopword Removal
    text = ' '.join(tokens)
    text = stopword_remover.remove(text)

    # 7. Tokenisasi kembali
    tokens = text.split()

    # 8. Stemming
    tokens = [stemmer.stem(token) for token in tokens]

    return tokens

In [22]:
df['Hasil_Preprocessing'] = df['Dokumen'].apply(preprocess_text)

df

,Dokumen,Hasil_Preprocessing
0,Keamanan siber sangat penting untuk melindungi...,"[aman, siber, sangat, penting, lindung, data, ..."
1,Internet of Things memungkinkan berbagai peran...,"[internet, of, things, mungkin, bagai, perangk..."
2,Perpustakaan digital menyediakan berbagai kole...,"[pustaka, digital, sedia, bagai, koleksi, buku..."
3,Komputasi awan menyediakan layanan penyimpanan...,"[komputasi, awan, sedia, layan, simpan, olah, ..."
4,E-Commerce memudahkan masyarakat melakukan tra...,"[ecommerce, mudah, masyarakat, laku, transaksi..."

In [23]:
for i in range(2):
    print("Dokumen", i + 1)
    print("Sebelum preprocessing:")
    print(df.loc[i, 'Dokumen'])

    print("\nSesudah preprocessing:")
    print(df.loc[i, 'Hasil_Preprocessing'])

    print("=" * 70)

Dokumen 1
Sebelum preprocessing:
Keamanan siber sangat penting untuk melindungi data pribadi dan sistem komputer dari serangan berbahaya.

Sesudah preprocessing:
['aman', 'siber', 'sangat', 'penting', 'lindung', 'data', 'pribadi', 'sistem', 'komputer', 'serang', 'bahaya']
======================================================================
Dokumen 2
Sebelum preprocessing:
Internet of Things memungkinkan berbagai perangkat terhubung ke internet dan saling bertukar data secara otomatis.

Sesudah preprocessing:
['internet', 'of', 'things', 'mungkin', 'bagai', 'perangkat', 'hubung', 'internet', 'saling', 'tukar', 'data', 'otomatis']
======================================================================

In [24]:
# Menghitung jumlah token sebelum preprocessing
df['Token_Sebelum'] = df['Dokumen'].apply(
    lambda x: len(x.lower().split())
)

# Menghitung jumlah token sesudah preprocessing
df['Token_Sesudah'] = df['Hasil_Preprocessing'].apply(
    lambda x: len(x)
)

# Menghitung persentase pengurangan token
df['Persentase_Pengurangan'] = (
    (df['Token_Sebelum'] - df['Token_Sesudah'])
    / df['Token_Sebelum']
) * 100

# Membulatkan menjadi 2 angka desimal
df['Persentase_Pengurangan'] = df['Persentase_Pengurangan'].round(2)

# Menampilkan hasil
df[['Token_Sebelum', 'Token_Sesudah', 'Persentase_Pengurangan']]

   Token_Sebelum  Token_Sesudah  Persentase_Pengurangan
0             14             11                   21.43
1             15             12                   20.00
2             14             13                    7.14
3             17             15                   11.76
4             15             13                   13.33

In [25]:
hasil_analisis = pd.DataFrame({
    'Dokumen': range(1, len(df) + 1),
    'Token Sebelum': df['Token_Sebelum'],
    'Token Sesudah': df['Token_Sesudah'],
    'Pengurangan (%)': df['Persentase_Pengurangan']
})

hasil_analisis

   Dokumen  Token Sebelum  Token Sesudah  Pengurangan (%)
0        1             14             11            21.43
1        2             15             12            20.00
2        3             14             13             7.14
3        4             17             15            11.76
4        5             15             13            13.33

In [26]:
for i, row in df.iterrows():
    print(f"Dokumen {i + 1}:")
    print("Asli       :", row['Dokumen'])
    print("Preprocessing:", row['Hasil_Preprocessing'])
    print()

Dokumen 1:
Asli       : Keamanan siber sangat penting untuk melindungi data pribadi dan sistem komputer dari serangan berbahaya.
Preprocessing: ['aman', 'siber', 'sangat', 'penting', 'lindung', 'data', 'pribadi', 'sistem', 'komputer', 'serang', 'bahaya']

Dokumen 2:
Asli       : Internet of Things memungkinkan berbagai perangkat terhubung ke internet dan saling bertukar data secara otomatis.
Preprocessing: ['internet', 'of', 'things', 'mungkin', 'bagai', 'perangkat', 'hubung', 'internet', 'saling', 'tukar', 'data', 'otomatis']

Dokumen 3:
Asli       : Perpustakaan digital menyediakan berbagai koleksi buku elektronik yang dapat diakses mahasiswa melalui jaringan internet.
Preprocessing: ['pustaka', 'digital', 'sedia', 'bagai', 'koleksi', 'buku', 'elektronik', 'dapat', 'akses', 'mahasiswa', 'lalu', 'jaring', 'internet']

Dokumen 4:
Asli       : Komputasi awan menyediakan layanan penyimpanan dan pengolahan data melalui jaringan internet tanpa harus menggunakan perangkat keras sendiri.
Preprocessing: ['komputasi', 'awan', 'sedia', 'layan', 'simpan', 'olah', 'data', 'lalu', 'jaring', 'internet', 'harus', 'guna', 'perangkat', 'keras', 'sendiri']

Dokumen 5:
Asli       : E-Commerce memudahkan masyarakat melakukan transaksi jual beli secara online dengan menggunakan berbagai metode pembayaran digital.
Preprocessing: ['ecommerce', 'mudah', 'masyarakat', 'laku', 'transaksi', 'jual', 'beli', 'online', 'guna', 'bagai', 'metode', 'bayar', 'digital']

In [27]:
print("""
Berdasarkan hasil preprocessing teks, setiap dokumen mengalami perubahan
dari teks asli menjadi kumpulan kata yang lebih sederhana. Tahapan yang
dilakukan meliputi case folding, pembersihan angka dan tanda baca,
tokenisasi, stopword removal, dan stemming. Stopword removal digunakan
untuk menghilangkan kata-kata umum yang kurang memberikan informasi,
sedangkan stemming mengubah kata menjadi bentuk dasarnya. Setelah proses
preprocessing, jumlah token pada setiap dokumen mengalami pengurangan.
Hal ini menunjukkan bahwa preprocessing dapat membuat data teks menjadi
lebih ringkas dan lebih siap digunakan untuk proses analisis teks
selanjutnya.
""")

Berdasarkan hasil preprocessing teks, setiap dokumen mengalami perubahan
dari teks asli menjadi kumpulan kata yang lebih sederhana. Tahapan yang
dilakukan meliputi case folding, pembersihan angka dan tanda baca,
tokenisasi, stopword removal, dan stemming. Stopword removal digunakan
untuk menghilangkan kata-kata umum yang kurang memberikan informasi,
sedangkan stemming mengubah kata menjadi bentuk dasarnya. Setelah proses
preprocessing, jumlah token pada setiap dokumen mengalami pengurangan.
Hal ini menunjukkan bahwa preprocessing dapat membuat data teks menjadi
lebih ringkas dan lebih siap digunakan untuk proses analisis teks
selanjutnya.

In [28]:
df

,Dokumen,Hasil_Preprocessing,Token_Sebelum,Token_Sesudah,Persentase_Pengurangan
0,Keamanan siber sangat penting untuk melindungi...,"[aman, siber, sangat, penting, lindung, data, ...",14,11,21.43
1,Internet of Things memungkinkan berbagai peran...,"[internet, of, things, mungkin, bagai, perangk...",15,12,20.00
2,Perpustakaan digital menyediakan berbagai kole...,"[pustaka, digital, sedia, bagai, koleksi, buku...",14,13,7.14
3,Komputasi awan menyediakan layanan penyimpanan...,"[komputasi, awan, sedia, layan, simpan, olah, ...",17,15,11.76
4,E-Commerce memudahkan masyarakat melakukan tra...,"[ecommerce, mudah, masyarakat, laku, transaksi...",15,13,13.33